### PR TITLE
Update tile.openstreetmap.org

### PR DESCRIPTION
**Pull request by Firefishy**
Update tile URL per: https://github.com/openstreetmap/operations/issues/737

### CODE REVIEW

**Comment by Firefishy** [comment]
@Monstrofil any chance you could merge this?

**Comment by Monstrofil** [comment]
@Firefishy hi, I actually found and changed couple more places where a|b|c links are used, I will push and deploy those changes within next couple of days.

**Comment by Firefishy** [comment]
Cool. I'll keep this PR open for now as a tracker, else feel free to close at any time.

**Comment by Monstrofil** [comment]
@Firefishy change is merged and deployed, all requests should go to the tile.* host now.

**Pull request closed without merging**
